# Generated by Django 5.0.3 on 2024-04-29 17:54

from django.db import migrations, models


def remove_address_and_rename_field(apps, schema_editor):
    User = apps.get_model('escuchamos', 'User')
    User.objects.all().update(address='') 


class Migration(migrations.Migration):

    dependencies = [
        ('escuchamos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_address_and_rename_field),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_verification_token',
            new_name='verification_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=6, blank=True, null=True),
        ),
    ]
