# Generated by Django 5.0.3 on 2024-05-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuchamos', '0004_role_permissions'),
        ('escuchamos', '0005_typepost'),
    ]

    operations = [
    ]
