# Generated by Django 5.0.3 on 2024-05-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuchamos', '0017_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='description',
        ),
        migrations.AlterField(
            model_name='input',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
