# Generated by Django 5.0.3 on 2024-05-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuchamos', '0018_remove_input_description_alter_input_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
    ]
