# Generated by Django 5.0.3 on 2024-05-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuchamos', '0020_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderStatuses',
            new_name='OrderStatus',
        ),
        migrations.AlterField(
            model_name='benefited',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benefiteds', to='escuchamos.activity'),
        ),
    ]
